### ISSUE TITLE
LOVE crushes after a long time

### ISSUE THREAD

**Issue by jgalazm** [lsst-ts/LOVE-integration-tools#19]
I suspect it is from the 400 scripts limit in the scriptqueue which makes the simulator.
The `scriptqueue-sim` gives a ` dds.DDSException: Failed to create participant  Return code: Error`.
However, the `love-manager` says that it `Can't contact LDAP server` and also that the IP `45.79.13.50` should be added to `ALLOWED_HOSTS `.

See the logs below and the attached file for the full logs (from `docker-compose logs > logs.txt`).
```
scriptqueue-sim    | #
scriptqueue-sim    | # Loading LSST Stack
scriptqueue-sim    | #
scriptqueue-sim    | # Loading sal environment
scriptqueue-sim    | SAL development environment is configured
scriptqueue-sim    | <<< Vortex OpenSplice HDE Release 6.9.181127OSS For x86_64.linux, Date 2018-11-28 >>>
scriptqueue-sim    | LSST middleware toolset environment v3.10.0 is configured
scriptqueue-sim    | #
scriptqueue-sim    | # Setting up sal, salobj and scriptqueue
scriptqueue-sim    | RemoteEvent(Script, 0, heartbeat) falling behind; read 15 messages
scriptqueue-sim    | Traceback (most recent call last):
scriptqueue-sim    |   File "/home/saluser/repos/ts_scriptqueue/tests/data/standard/script1", line 6, in <module>
scriptqueue-sim    |     TestScript.main(descr="standard script1")
scriptqueue-sim    |   File "/home/saluser/repos/ts_scriptqueue/python/lsst/ts/scriptqueue/base_script.py", line 149, in main
scriptqueue-sim    |     script = cls(**kwargs)
scriptqueue-sim    |   File "/home/saluser/repos/ts_scriptqueue/python/lsst/ts/scriptqueue/test_utils.py", line 45, in __init__
scriptqueue-sim    |     super().__init__(index=index, descr=descr)
scriptqueue-sim    |   File "/home/saluser/repos/ts_scriptqueue/python/lsst/ts/scriptqueue/base_script.py", line 75, in __init__
scriptqueue-sim    |     super().__init__("Script", index, do_callbacks=True)
scriptqueue-sim    |   File "/home/saluser/repos/ts_salobj/python/lsst/ts/salobj/controller.py", line 137, in __init__
scriptqueue-sim    |     domain = Domain()
scriptqueue-sim    |   File "/home/saluser/repos/ts_salobj/python/lsst/ts/salobj/domain.py", line 128, in __init__
scriptqueue-sim    |     self.participant = dds.DomainParticipant(qos=participant_qos)
scriptqueue-sim    |   File "dds.pyx", line 1661, in dds.DomainParticipant.__cinit__
scriptqueue-sim    | dds.DDSException: Failed to create participant  Return code: Error
```
```
love-manager       | Invalid HTTP_HOST header: '45.79.13.50:8000'. You may need to add '45.79.13.50' to ALLOWED_HOSTS.
love-manager       | 2019-07-02 06:19:58,240 ERROR    Invalid HTTP_HOST header: '45.79.13.50:8000'. You may need to add '45.79.13.50' to ALLOWED_HOSTS.
love-manager       | Bad Request: /favicon.ico
love-manager       | 2019-07-02 06:19:58,443 WARNING  Bad Request: /favicon.ico
love-manager       | Unauthorized: /manager/api/validate-token/
love-manager       | 2019-07-02 12:46:47,766 WARNING  Unauthorized: /manager/api/validate-token/
love-manager       | 2019-07-02 12:46:49,301 WARNING  Caught LDAPError while authenticating test: SERVER_DOWN({'desc': "Can't contact LDAP server", 'errno': 107, 'info': 'Transport endpoint is not connected'},)
love-manager       | Bad Request: /manager/api/get-token/
```

[logs.txt](https://github.com/lsst-ts/LOVE-integration-tools/files/3350197/logs.txt)

**Comment by jgalazm** [comment]
Running `docker start lsst-ldap` on the linode machine also gives:

```
Error response from daemon: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused"
Error: failed to start containers: lsst-ldap
```

**Comment by jgalazm** [comment]
Idea to replicate the error:
Make it fail quickly by sending many scripts with a very short duration. For example, with  `wait_time: 0.01` and with `asyncio.sleep(0.01)`.

**Comment by jgalazm** [comment]
This requires `service docker restart`, otherwise:
```
ERROR: for scriptqueue-sim  cannot stop container: 6c55ac4e9e69921a9f97fea89c86aae23f9bd23f23e73a99f4f801bee1d97faf: Cannot kill container 6c55ac4e9e69921a9f97fea89c86aae23f9bd23f23e73a99f4f801bee1d97faf: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

```

**Comment by jgalazm** [comment]
```
love@dev:~$ service docker restart
Failed to restart docker.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status docker.service' for details.
```
